version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "11:00"
  open-pull-requests-limit: 10
  assignees:
  - chadjvw
  versioning-strategy: increase
  ignore:
  - dependency-name: "@types/aws-lambda"
    versions:
    - 8.10.68
    - 8.10.71
  - dependency-name: typescript
    versions:
    - 4.1.3
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.10
  - dependency-name: "@babel/plugin-proposal-class-properties"
    versions:
    - 7.12.1
  - dependency-name: "@babel/plugin-proposal-object-rest-spread"
    versions:
    - 7.12.1
  - dependency-name: webpack
    versions:
    - 4.44.2
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
